# Generated by Django 5.1.4 on 2025-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdwatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostlatentprofile',
            name='birdwatch_status',
            field=models.CharField(blank=True, default='unknown', max_length=20),
        ),
    ]
