# Generated by Django 5.1.4 on 2025-01-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='validity',
            field=models.FloatField(default=0),
        ),
    ]
