# Generated by Django 5.1.4 on 2025-01-11 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='bet',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
