# Generated by Django 5.1.4 on 2025-01-11 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newspost_bet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='reacted_by',
            field=models.ManyToManyField(blank=True, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='impact',
            field=models.FloatField(default=0.0),
        ),
    ]
