# Generated by Django 5.1.4 on 2025-03-25 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspost_reacted_by_alter_newspost_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='birdwatch_validity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
